# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNNavigationExample' do
  # use_frameworks!

  # Pods for RN Nav Example
  pod 'React', path: '../node_modules/react-native/', subspecs: [
    'Core',
    'RCTText',
    'RCTWebSocket',
    'RCTNetwork'
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
end
